name: Release

on:
  push:
    tags:
      - 'v*'  # 仅在推送 v 开头的 tag 时触发

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # - name: Install dependencies
        # run: npm install

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup
        run: npm i -g @antfu/ni

      - name: Install
        run: ni --no-frozen-lockfile

      - name: Run release-it
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub 自动生成的 token
        run: npx release-it